on: [push]

jobs:
  check-quality:
    runs-on: ubuntu-latest
    name: A job to check my code quality
    steps:
    - name: Check code meets quality standards
      id: code-inspector
      uses: codeinspectorio/github-action@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        ci-access-key: ${{ secrets.CODE_INSPECTOR_ACCESS_KEY }}
        ci-secret-key: ${{ secrets.CODE_INSPECTOR_SECRET_KEY }}
        access-key: ${{ secrets.CODE_INSPECTOR_ACCESS_KEY }}
        secret-key: ${{ secrets.CODE_INSPECTOR_SECRET_KEY }}
        min-quality-grade: 'WARNING'
        min-quality-score: '50'
        max-defects-rate: '0.0001'
        max-complex-functions-rate: '0.0001'
        max-long-functions-rate: '0.0001'
        project-name: ''
        max-timeout-sec: '600'
